version: '3'
services:
  
  #PHP Service
  app:
    build:
      context: ./docker/php_8.1
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - .docker/php_8.1/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge