version: '3.8'
services:
  
  #PHP Service
  app:
    build:
      context: ./docker/php_8.1
      dockerfile: Dockerfile
    container_name: ${COMPOSE_APP_NAME}-app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/lara-docker
    volumes:
       - ${MARKETING_API_PATH}/:/var/www/lara-docker
       - ./docker/php_8.1/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx-webserver
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    working_dir: /var/www
    volumes:
      - ${MARKETING_API_PATH}/:/var/www/lara-docker
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge